version: 0.2

phases:
    install:
        commands:
            - project_name=document_aggregator
            - /bin/bash codebuild/install.sh
    pre_build:
        commands:
            - /bin/bash codebuild/prebuild.sh
    build:
        commands:
            - /bin/bash codebuild/build.sh
    post_build:
        commands:
            - /bin/bash codebuild/postbuild.sh
            
artifacts:
    files:
        - scraper/document_scraper.py.zip
        - scraper/scraper_deploy.yml
        - web/index.html
        - web/web_deploy.yml
    secondary-artifacts:
        BuildArtifact:
            files:
                - scraper/document_scraper.py.zip
                - scraper/scraper_deploy.yml