version: 0.2

phases:
    install:
        commands:
            - echo "Entering installation phase"
            - ./setup_virtual_env.sh
            - echo "Exiting installation phase"
    pre_build:
        commands:
            - echo "Entering test phase"
            - echo "Exiting test phase"
    build:
        commands:
            - echo "Entering build phase"
            - echo "Building scraper"
            - python3 build-scraper.py
            - echo "Finished building scraper"
            - echo "Building webpage"
            - python3 build-webpage.py
            - echo "Finished building webpage"
            - echo "Exiting build phase"
    post_build:
        commands:
            - echo "Entering post-build phase"
            - echo "Exiting post-build phase"
            
artifacts:
    files:
        - scraper/web_scraper_deploy.yml
    secondary-artifacts:
        BuildArtifact:
            files:
                - scraper/web_scraper_deploy.yml