version: 0.2

phases:
    install:
        commands:
            - echo "Entering installation phase"
            - pip install boto3 --upgrade --user
            - pip3 install boto3 --upgrade --user
            - echo "Exiting installation phase"
    pre_build:
        commands:
            - echo "Entering test phase"
            - python3 -c "from scraper.test import lambda_handler; lambda_handler(\"dummy event\", \"dummy context\")"
            - echo "Exiting test phase"
    build:
        commands:
            - echo "Entering build phase"
            - python3 build.py
            - echo "Exiting build phase"
    post_build:
        commands:
            - echo "Entering post-build phase"
            - echo "Exiting post-build phase"
            
artifacts:
    files:
        - "scaper/web-scraper-deploy.yaml"
    name: "doc-aggregator-build-artifact"
    discard-paths: no
    base-directory: "s3::documentation-aggregator/documentation-aggreg/BuildArti"