version: 0.2

phases:
    install:
        commands:
            - project_name=document_aggregator
            - /bin/bash setup_virtual_env.sh $project_name
    pre_build:
        commands:
    build:
        commands:
            - echo $project_name
            - /bin/bash ls
            - /bin/bash which source
            - /bin/bash which python3
            - /bin/bash which python
            - ls
            - which source
            - which python3
            - which python
            - echo "Building scraper"
            - /bin/bash source $project_name/bin/activate && python3 build-scraper.py
            - echo "Finished building scraper"
            - echo "Building webpage"
            - /bin/bash source $project_name/bin/activate && build-webpage.py
            - echo "Finished building webpage"
    post_build:
        commands:
            - /bin/bash cleanup_and_commit.sh
            
artifacts:
    files:
        - scraper/web_scraper_deploy.yml
    secondary-artifacts:
        BuildArtifact:
            files:
                - scraper/web_scraper_deploy.yml