version: 0.2

phases:
    install:
        commands:
            - project_name=document_aggregator
            - /bin/bash codebuild/scripts/install.sh
    pre_build:
        commands:
            - /bin/bash codebuild/scripts/prebuild.sh
    build:
        commands:
            - /bin/bash codebuild/scripts/build.sh
    post_build:
        commands:
            - /bin/bash codebuild/scripts/postbuild.sh
            
artifacts:
    files:
        - cloudformation/scraper_deploy.yml
    secondary-artifacts:
        BuildArtifact:
            files:
                - cloudformation/scraper_deploy.yml