AWSTemplateFormatVersion: '2010-09-09'
Description: "Cloudformation Deployment segments for the scraper side of the document_aggregator"

Parameters:
  ReadCapacityUnits:
    Description: "Provisioned Read Throughput for DynamoDB"
    Type: "Number"
    Default: 1
    MinValue: 1
    MaxValue: 5
    ConstraintDescription: "Keep throughput between 1 and 5 to stay within free tier"
  WriteCapacityUnits:
    Description: "Provisioned Write Throughput for DynamoDB"
    Type: "Number"
    Default: 1
    MinValue: 1
    MaxValue: 5
    ConstraintDescription: "Keep throughput between 1 and 5 to stay within free tier"
    
Resources:
  TopicTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "DocumentationAggregatorTopics"
      AttributeDefinitions:
        -
          AttributeName: "Id"
          AttributeType: "N"
        -
          AttributeName: "Topic"
          AttributeType: "S"      
      KeySchema:
        -
          AttributeName: "Id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits:
          Ref: ReadCapacityUnits
        WriteCapacityUnits:
          Ref: WriteCapacityUnits
      GlobalSecondaryIndexes:
        -
          IndexName: "Topic-DateSubmitted-DateProcessed"
          KeySchema:
            -
             AttributeName: "Topic"
             KeyType: "HASH"
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits:
              Ref: ReadCapacityUnits
            WriteCapacityUnits:
              Ref: WriteCapacityUnits
          
  BasicLambdaScraper:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "BasicLambdaScraper"
      Description: "Basic lambda function for scraper"
      Runtime: "python3.6"
      Code:
        S3Bucket: "documentation-aggregator"
        S3Key: "deploy/scraper/document_scraper.py"
      Handler: "document_scraper.lambda_handler"
      Layers:
        - "arn:aws:lambda:us-east-1:353290830413:layer:headlessChromium:1"
        - "arn:aws:lambda:us-east-1:353290830413:layer:scraping:16"
      Role: "arn:aws:iam::353290830413:role/lambda_test_role"
      Timeout: 300
      
      
