AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudformation Deployment segments for the scraper side of the document_aggregator
Parameters:
  ReadCapacityUnits:
    ConstraintDescription: Keep throughput between 1 and 5 to stay within free tier
    Default: 1
    Description: Provisioned Read Throughput for DynamoDB
    MaxValue: 5
    MinValue: 1
    Type: Number
  WriteCapacityUnits:
    ConstraintDescription: Keep throughput between 1 and 5 to stay within free tier
    Default: 1
    Description: Provisioned Write Throughput for DynamoDB
    MaxValue: 5
    MinValue: 1
    Type: Number
Resources:
  GetHTMLFromURL:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: ""
      Description: Basic lambda function for scraper
      FunctionName: BasicLambdaScraper
      Handler: index.lambda_handler
      Layers:
        - arn:aws:lambda:us-east-1:353290830413:layer:headlessChromium:1
        - arn:aws:lambda:us-east-1:353290830413:layer:scraping:31
      Role: arn:aws:iam::353290830413:role/lambda_test_role
      Runtime: python3.6
      MemorySize: 512
      Timeout: 300
  TopicTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: Id
        AttributeType: N
      - AttributeName: Topic
        AttributeType: S
      GlobalSecondaryIndexes:
      - IndexName: Topic-DateSubmitted-DateProcessed
        KeySchema:
        - AttributeName: Topic
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits:
            Ref: ReadCapacityUnits
          WriteCapacityUnits:
            Ref: WriteCapacityUnits
      KeySchema:
      - AttributeName: Id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits:
          Ref: ReadCapacityUnits
        WriteCapacityUnits:
          Ref: WriteCapacityUnits
      TableName: DocumentationAggregatorTopics
