AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudformation Deployment segments for the scraper side of the document_aggregator
Parameters:
  ReadCapacityUnits:
    ConstraintDescription: Keep throughput between 1 and 5 to stay within free tier
    Default: 1
    Description: Provisioned Read Throughput for DynamoDB
    MaxValue: 5
    MinValue: 1
    Type: Number
  WriteCapacityUnits:
    ConstraintDescription: Keep throughput between 1 and 5 to stay within free tier
    Default: 1
    Description: Provisioned Write Throughput for DynamoDB
    MaxValue: 5
    MinValue: 1
    Type: Number
Resources:
  GetHTMLFromURL:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: ""
      Description: Returns the html associated with a particular url.
      FunctionName: GetHTMLFromURL
      Handler: index.lambda_handler
      Layers:
        - arn:aws:lambda:us-east-1:353290830413:layer:headlessChromium:1
        - arn:aws:lambda:us-east-1:353290830413:layer:scraping:31
      Role: arn:aws:iam::353290830413:role/lambda_test_role
      Runtime: python3.6
      MemorySize: 512
      Timeout: 300
  QueryTopic:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: ""
      Description: Returns a list of links on a particular topic taken from google.
      FunctionName: QueryTopic
      Handler: index.lambda_handler
      Layers:
        - arn:aws:lambda:us-east-1:353290830413:layer:boto3:38
        - arn:aws:lambda:us-east-1:353290830413:layer:scraping:31
      Role: arn:aws:iam::353290830413:role/lambda_test_role
      Runtime: python3.6
      MemorySize: 128
      Timeout: 600
  ExtractText:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: ""
      Description: Extracts visible text from the html returned by the provided url.
      FunctionName: ExtractText
      Handler: index.lambda_handler
      Layers:
        - arn:aws:lambda:us-east-1:353290830413:layer:boto3:38
        - arn:aws:lambda:us-east-1:353290830413:layer:scraping:31
      Role: arn:aws:iam::353290830413:role/lambda_test_role
      Runtime: python3.6
      MemorySize: 128
      Timeout: 600
  ResearchTopic:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: ""
      Description: Takes a topic, searches google for related links, and extracts text from the related links.
      FunctionName: ResearchTopic
      Handler: index.lambda_handler
      Layers:
        - arn:aws:lambda:us-east-1:353290830413:layer:boto3:38
      Role: arn:aws:iam::353290830413:role/lambda_test_role
      Runtime: python3.6
      MemorySize: 128
      Timeout: 600
  TopicTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: Id
        AttributeType: N
      - AttributeName: Topic
        AttributeType: S
      GlobalSecondaryIndexes:
      - IndexName: Topic-DateSubmitted-DateProcessed
        KeySchema:
        - AttributeName: Topic
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits:
            Ref: ReadCapacityUnits
          WriteCapacityUnits:
            Ref: WriteCapacityUnits
      KeySchema:
      - AttributeName: Id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits:
          Ref: ReadCapacityUnits
        WriteCapacityUnits:
          Ref: WriteCapacityUnits
      TableName: DocumentationAggregatorTopics
  TopicResearchEventMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: arn:aws:dynamodb:us-east-1:353290830413:table/DocumentationAggregatorTopics/stream/2019-05-07T20:03:36.640
      FunctionName: ResearchTopic
      StartingPosition: LATEST
