AWSTemplateFormatVersion: '2010-09-09'
Description: Testing CloudFormation for general systems deployment
Resources:
  LambdaTest:
    Properties:
      Code: {ZipFile: ""}
      Description: Testing deploying code straight to aws lambda through code pipeline
      Handler: index.lambda_handler
      MemorySize: 128
      ReservedConcurrentExecutions: 5
      Role: arn:aws:iam::353290830413:role/lambda_test_role
      Runtime: python3.6
      Tags:
      - {Key: project, Value: document_aggregator}
      TracingConfig: {Mode: Active}
    Type: AWS::Lambda::Function
