AWSTemplateFormatVersion: "2019-03-5"
Description: "Testing CloudFormation for general systems deployment"
Resources:
    LambdaTest:
        Type: "AWS::Lambda::Function"
        Properties: 
          Code:
            S3Bucket: "documentation-aggregator"
            S3Key: "scraper/test.py"
          Description: "Testing deploying code straight to aws lambda through code pipeline
          Handler: ".scraper.test.lambda_handler"
          MemorySize: 64
          ReservedConcurrentExecutions: 5
          Role: "arn:aws:iam::353290830413:role/lambda_test_role"
          Runtime: "python3.6"
          TracingConfig:
            Mode:
                "Active"
          Tags: 
          -
            Key: "project"
            Value: "document_aggregator"

