AWSTemplateFormatVersion: "2010-09-09"
Description: "Testing CloudFormation for general systems deployment"
Resources:
    LambdaTest:
        Type: "AWS::Lambda::Function"
        Properties: 
          Code:
            ZipFile: |
               import boto3
               import json
               print('Loading Test Function')
               def lambda_handler(event, context):
                  message = "Testing lambda and code pipeline"
                  print(message)
                  return message
          Description: "Testing deploying code straight to aws lambda through code pipeline"
          Handler: "scraper.test.lambda_handler"
          MemorySize: 128
          ReservedConcurrentExecutions: 5
          Role: "arn:aws:iam::353290830413:role/lambda_test_role"
          Runtime: "python3.6"
          TracingConfig:
            Mode:
                "Active"
          Tags: 
          -
            Key: "project"
            Value: "document_aggregator"

