AWSTemplateFormatVersion: '2010-09-09'
Description: "Cloudformation Deployment for website side of the document_aggregator"

Resources:
  AggregatorWebPageDeadLetterQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "AggregatorWebPageDeadLetterQueue"
  GetTopics: 
    Type: "AWS::Lambda::Function"
    Properties: 
      Code: 
        ZipFile: ""
      Description: "Get the topics currently in DynamoDB"
      FunctionName: GetTopics
      Handler: index.lambda_handler
      Layers: 
        - "arn:aws:lambda:us-east-1:353290830413:layer:boto3:38"
      MemorySize: 128
      Role: "arn:aws:iam::353290830413:role/lambda_test_role"
      Runtime: python3.6
      Timeout: 600
      DeadLetterConfig:
        TargetArn:
          Fn::GetAtt: [ AggregatorWebPageDeadLetterQueue, Arn ]